controllers/routes.py
import os
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, redirect, flash, jsonify, send_from_directory
from models import dados_remedios, dados_diarios, dados_medicamentos, dados_api, config
from utils import utils

main = Blueprint('main', __name__, static_folder="static", template_folder="templates")

@main.route("/", methods=["GET"])
def index():
    editando = request.args.get('editando')
    editando = int(editando) if editando else None

    remedios_db = dados_remedios.get_remedios()
    diarios_db = dados_diarios.get_diarios()
    medicamentos = dados_medicamentos.get_medicamentos()

    remedios, diarios = utils.format_data(remedios_db, diarios_db)

    return render_template("index.html", diarios=diarios, remedios=remedios, medicamentos=medicamentos,
                           editando=editando)


@main.route("/add_diario", methods=["POST"])
def add_diario():
    texto = request.form.get("texto", "").strip()
    tomou = 'remedio' in request.form
    data = request.form.get("data")

    remedio = False

    texto_diario = False

    if not data or data.strip() == "":
        data = datetime.now().strftime("%Y-%m-%d")

    if texto:
        dados_diarios.insert_diarios(texto, data)
        texto_diario = True
    if tomou and data:
        tomou_remedio = dados_remedios.select_tomou_remedio(data)
        if tomou_remedio:
            remedio = True
        else:
            dados_remedios.tomou_remedio(tomou, data)

    if not texto and not tomou:
        flash("Preencha pelo menos um campo!", "erro")
        return redirect("/")

    if not remedio:
        flash('Entrada registrada com sucesso!', "sucesso")

    if texto_diario and remedio:
        flash("Diário salvo! Mas o remédio já foi registrado hoje.", "info")
    elif remedio:
        flash("Você já registrou hoje!", "erro")
    elif texto_diario or tomou:
        flash("Entrada registrada com sucesso!", "sucesso")

    config.get_db().commit()
    return redirect(url_for("main.index"))


@main.route("/delete_diario/<int:id>")
def delete_diario(id):
    dados_diarios.delete_diario(id)
    return redirect(url_for("main.index"))


@main.route("/delete_remedio/<int:id>")
def delete_remedio(id):
    dados_remedios.delete_remedios(id)
    return redirect(url_for("main.index"))


@main.route("/add_medicamento", methods=["POST"])
def add_medicamento():
    texto = request.form.get("texto", "").strip()
    quantidade = request.form.get("quantidade", "").strip()
    dados_remedios.insert_remedio(texto, quantidade)
    return redirect(url_for("main.index"))


@main.route("/delete_medicamento/<int:id>")
def delete_medicamento(id):
    dados_medicamentos.delete_medicamento(id)
    return redirect(url_for("main.index"))


@main.route("/atualizar/<int:id>", methods=["POST"])
def atualizar_diario(id):
    novo_texto = request.form.get("texto", "").strip()
    dados_diarios.atualizar_diario(novo_texto, id)
    return redirect(url_for("main.index"))


@main.route("/api/dados", methods=["GET"])
def api_diarios():
    return dados_api.get_dados_api()

@main.route("/calendario/", defaults={"filename": "index.html"})
@main.route("/calendario/<path:filename>")
def serve_calendario(filename):
    path = os.path.join("static", "calendario")
    return send_from_directory(path, filename)

@main.route('/<path:path>')
def static_files(path):
    return send_from_directory(main.static_folder, path)


@main.route("/api/dados/<int:id>", methods=["PUT"])
def atualizar_dados(id):
    dados = request.get_json()
    novo_texto = dados.get("texto", "").strip()
    if not novo_texto:
        return jsonify({"erro": "Texto vazio"}), 400

    dados_diarios.atualizar_diario_react(novo_texto, id)
    return jsonify({"status": "sucesso", "id": id, "texto": novo_texto})


@main.route('/backup')
def backup():
    config.backup()
    return redirect(url_for("main.index"))

templates/index.html
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dose de Mim</title>
    <link rel="shortcut icon" href="../static/img/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="../static/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
      <nav>
        <a href="javascript:void(0);" class="icon" onclick="toggleMenu()">
          <i class="fa fa-bars"></i>
        </a>
        <ul id="menu">
          <li><a href="{{ url_for('main.serve_calendario')}}">Histórico</a></li>
          <li>⭐</li>
          <li><a href="{{ url_for('main.backup') }}">Backup</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <div class="bloco-1">
        <div class="formulario">
        <form class="form_diario" action="/add_diario" method="post">
          <label class="label-texto" for="texto">Diário</label>
          <textarea name="texto" id="texto" cols="30" rows="10"></textarea>
      
          <div class="remedio">
            <label for="remedio">Tomou o remédio?</label>
            <input type="checkbox" name="remedio" id="remedio">

            <input type="date" name="data" id="data">
          </div>
          
          <button type="submit" value="Enviar">Enviar</button>
        </form>

        
      </div>

      <div class="conteudo-3">
        <div class="conteudo-1" id="medicamentos">
          <h2>Medicamentos</h2>
          <ul>
            <form action="/add_medicamento" method="post">
              <div class="inputs">
                <input type="text" name="texto" id="texto" placeholder="Nome do medicamento" required>
                <input type="number" name="quantidade" id="quantidade" placeholder="Quantidade" required>
              </div>
              <button type="submit">Adicionar</button>
            </form>

            <ul>
              {% for id, texto, quantidade in medicamentos %}
              <li>
                {{ texto | title}} - {{ quantidade}} unidades
                <a href="javascript:void(0);" onclick="askDelete('/delete_medicamento/{{ id }}')">Apagar</a>
              </li>
              {% endfor %}
            </ul>
        </div>
      </div>
      </div>
      
    
      <div class="resposta">
        <div class="conteudo-1">
          <h2>Entradas do Diário</h2>
          <ul>
            {% for d in diarios %}
            <li>
              {% if d.id == editando %}
              <form method="POST" action="{{ url_for('main.atualizar_diario', id=d.id) }}">
                <textarea name="texto" rows="4" cols="50">{{ d.texto }}</textarea><br>
                <button type="submit">Salvar</button>
                <a href="{{ url_for('main.index') }}">Cancelar</a>
              </form>
              {% else %}
              {{ d.data }}
              <button onclick="openModal(`{{ d.texto | escape }}`)">Ler</button>
              <a href="{{ url_for('main.index', editando=d.id) }}">Editar</a>
              <a href="javascript:void(0);" onclick="askDelete('/delete_diario/{{ d.id }}')">Apagar</a>
              {% endif %}
            </li>
            {% endfor %}
          </ul>
        </div>

        <div class="conteudo-2">
          <h2>Registro de Remédios</h2>
          <ul>
            {% for r in remedios %}
            <li><strong>{{r.data}}</strong> | ✅ Tomou
              <a href="javascript:void(0);" onclick="askDelete(`/delete_remedio/{{ r.id }}`)">Apagar</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
     
      <!-- Modais -->
      <div id="modal" class="modal" style="display: none;">
        <div class="modal-content">
          <p id="modal-texto"></p>
          <button onclick="closeModal()">Fechar</button>
        </div>
      </div>
    
      <div id="confirmModal" class="modal" style="display:none;">
        <div class="modal-content">
          <p>Você tem certeza que deseja apagar esta entrada?</p>
          <button id="confirmDelete">Sim, apagar</button>
          <button onclick="closeConfirmModal()">Cancelar</button>
        </div>
      </div>

      <!-- Mensagens -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% for category, message in messages %}
      <div class="mensagem-{{ category }}">{{ message }}</div>
      {% endfor %}
      {% endwith %}

    </main>

    <img class="sun" src="../static/img/sun.png">

    <script src="../static/script.js"></script>
</body>
</html>